config/routes.rb
CappUsa::Application.routes.draw do
	
	resources :audio_mp3s
	resources :audio_contents

	devise_for :users,:controllers => {:registrations => "registrations"}, :path_names => { :sign_in => 'login' }
	match 'users/activate' => "users#activate", :via => :GET

	match '/2016-conference-signup', :to => "signups#index", :via => :get
	resources :signups, :except => [:new, :edit, :destroy, :update] do
		collection do 
			get :confirm
			get :error
		end
	end

	resources :sent_email_messages, :path => "mail" do
		member do
			post :send
		end
	end
	resources :contact_lists do
		collection do
			get :by_type
			get :popup
			get :user_list
		end
	end
	resources :static_contact_lists do
		member do
			post :add_contact
			post :remove_contact
			get :user_list
		end
	end
	namespace :admin do
		resources :blocks
		resources :chapters
		resources :contemporary_issues
		resources :encyclicals
		resources :events do
			member do
				get 'user_list'
			end

			resources :attendees_events do
				member do
					put "clear_cc_info"
				end
			end
		end
		resources :locations
		resources :audio_contents
		resources :audio_mp3s
		resources :menu_items
		resources :pages
		resources :person_types
		resources :principles
		resources :papal_addresses
		resources :prism_types
		resources :role_types
		resources :stories
		resources :thoughts
		resources :feed_sources
		resources :users do
			collection do
				post 'search'
			end
			member do
				post 'activate'
			end
		end
		resources :questions do
		collection do
			get 'title'
			get 'type'
			get 'summary'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
		resources :content_fragments do
			collection do
				get 'type_options/:content_fragment_type', :action => 'type_options'
			end
		end
		resources :contacts do
			collection do
				get 'raw'
			end
			member do
				post 'upgrade'
			end
		end
	end

	resources :contemporary_issues do
		member do
			get 'view'
		end
	end
	resources :encyclicals, :path => "social_encyclicals" do
		collection do
			get 'published'
			get 'popup'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
	resources :events do
		member do
			post 'advanced_rsvp'
			post 'rsvp'
			post 'unrsvp'
			get 'thanks'
		end
		collection do
			get 'past'
		end
	end
	resources :locations
	resources :person_types
	resources :principles
	resources :prism_types
	resources :role_types
	resources :stories, :path => "news"
	resources :papal_addresses
	resources :feed_entries
	resources :thoughts, :path => "social_thought"
	resources :contacts
	resources :users

	match 'display' => 'audio_contents#display'

	match 'what_is_cst' => 'home#what_is_cst'
	match 'study_center' => 'home#study_center'
	match 'about_us/capp_usa_team' => 'home#about_us_capp_usa_team'
	match 'search' => 'search#index'
	match 'encyclicals/:id/chapter/:chapter/references' => 'encyclicals#chapter_references'
	match 'encyclicals/popup' => 'encyclicals#popup'

	match 'profile' => "users#edit", :via => :get
	match 'profile' => "users#update", :via => :put

	post 'paypal_ipn', :to => 'paypal_ipn#index', :as => 'paypal_ipn'

	match '*url' => 'pages#view'

	root :to => 'home#index'



	# See how all your routes lay out with "rake routes"

	# This is a legacy wild controller route that's not recommended for RESTful applications.
	# Note: This route will make all actions in every controller accessible via GET requests.
	# match ':controller(/:action(/:id(.:format)))'
end

app/controllers/admin/events_controller.rb
require 'csv'

class Admin::EventsController < ApplicationController

	before_filter :require_admin!

	respond_to :html

	def index
		respond_with(@events = Event.order(:start_date))
	end

	def user_list
		@event = Event.find(params[:id])
		csv_data = CSV.generate do |csv|
			csv << ["Last Name","First Name","Occupation","Address","City","Zip","Email","Telephone","Fax","Mobile","Attendee Type","Attendee Count","Attendee Dinner Count","Guest Name","Amount Paid","Payment Method"]
			@event.attendees_events.includes(:attendee).each do |attendee_event|
				csv << [
					attendee_event.last_name,
					attendee_event.first_name,
					attendee_event.occupation,
					attendee_event.address,
					attendee_event.city,
					attendee_event.zip,
					attendee_event.email,
					attendee_event.telephone,
					attendee_event.fax,
					attendee_event.mobile,
					attendee_event.attendee_type,
					attendee_event.count,
					attendee_event.dinner_count,
					attendee_event.guest_name,
					ActionController::Base.helpers.number_to_currency(attendee_event.total_cost),
					attendee_event.payment_method
				]
			end
		end
		send_data csv_data,
			:type => 'text/csv; charset=iso-8859-1; header=present',
			:disposition => "attachment; filename=event_#{@event.id}_user_list.csv"
	end

	def show
		respond_with(@event = Event.find(params[:id]))
	end

	def new
		respond_with(@event = Event.new)
	end

	def create
		respond_with(@event = Event.create(params[:event]), :location => admin_events_url)
	end

	def edit
		respond_with(@event = Event.find(params[:id]))
	end

	def update
		respond_with(@event = Event.update(params[:id], params[:event]), :location => event_path(@event))
	end

	def destroy
		respond_with(@event = Event.delete(params[:id]), :location => admin_events_url)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	respond_to :html

	def index
		@events = Event.upcoming
		process_events_search
	end

	def past
		@events = Event.past
		process_events_search
	end

	def show
		@thanks = params.has_key?(:thanks) && params[:thanks] == '1'
		flash[:notice] = 'Thank you for registering for this event.' if @thanks
		session[:return_url] = request.url unless current_user
		@event = Event.find(params[:id])
		sql ="SELECT * FROM events WHERE id IN (SELECT related_event_id FROM relateds_events WHERE event_id="+@event.id.to_s+")"
		@teaser_events = Event.find_by_sql sql
		respond_with(@event)
	end

	def thanks
		@payment_method = params[:payment_method] rescue nil
		respond_with(@event = Event.find(params[:id]))
	end

	def advanced_rsvp
		@event = Event.find(params[:id])

		@payment_method = params[:payment_method]
		@attendee_type = params[:attendee_type]
		@attendee_type = "regular" unless Event.attendee_types.include?(@attendee_type)
		@total_price = Event.EVENT_34_PRICE
		if @attendee_type != "regular"
			@total_price = Event.EVENT_34_OTHER_PRICE
		end
		@dinners = params[:dinner].to_i
		@guest = params.has_key?("guest")
		@count = 1
		if @guest
			@count = 2
			@total_price += Event.EVENT_34_GUEST_PRICE
		end
		@total_price += (@dinners * Event.EVENT_34_DINNER_PRICE)

		if (@event.spots_left - @count) < 0
			redirect_to event_url(@event), :alert => 'There are no spots available for that event.'
			return
		end

		if @payment_method == "paypal"
			payment_confirmation = PaymentConfirmation.new
			payment_confirmation.event = @event
			if user_signed_in?
				payment_confirmation.user = current_user
			end
			if payment_confirmation.save
				item_name = "#{@event.title} (#{@price_title})"
				invoice_id = payment_confirmation.id
				price = Event.EVENT_34_PRICE
				if @attendee_type != "regular"
					price = Event.EVENT_34_OTHER_PRICE
				end

				data = {
					"quanitity_1" => "1",
					"amount_1" => price,
					"item_name_1" => "Registration Fee"
				}

				if @dinners > 0
					data["quantity_2"] = @dinners
					data["amount_2"] = Event.EVENT_34_DINNER_PRICE
					data["item_name_2"] = "Dinner Fee"
				end

				if @guest && @dinners == 0
					data["quantity_2"] = "1"
					data["amount_2"] = Event.EVENT_34_GUEST_PRICE
					data["item_name_2"] = "Guest Registration Fee"
				end

				if @guest && @dinners > 0
					data["quantity_3"] = "1"
					data["amount_3"] = Event.EVENT_34_GUEST_PRICE
					data["item_name_3"] = "Guest Registration Fee"
				end

				session[:guest_name] = params[:guest_name]
				session[:attendee_type] = params[:attendee_type]

				redirect_to "#{paypal_url(@event, invoice_id, 0)}&#{data.to_query}"
				return
			else
				redirect_to event_path(@event), :alert => "Error redirecting to paypal for payment."
				return
			end
		else
			@attendee_event = AttendeesEvent.new(params[:attendees_event])
			@attendee_event.attendee_type = @attendee_type
			@attendee_event.event = @event
			@attendee_event.count = @count
			@attendee_event.total_cost = @total_price
			@attendee_event.created_at = Time.now
			@attendee_event.updated_at = Time.now
			@attendee_event.payment_method = @payment_method
			@attendee_event.guest_name = params[:guest_name]
			@attendee_event.dinner_count = @dinners
			@attendee_event.cc_number = params[:attendees_event][:cc_number]
			@attendee_event.cc_month = params[:attendees_event][:cc_month]
			@attendee_event.cc_year = params[:attendees_event][:cc_year]

			if @attendee_event.save
				UserMailer.event_registered_user(@event, @attendee_event).deliver
				UserMailer.event_registered_admin(@event, @attendee_event, nil).deliver
				redirect_to thanks_event_path(@event, :payment_method => @attendee_event.payment_method, :amount => @total_price), :notice => 'You have registered to attend the event.'
			else
				render :action => "show"
			end
		end
	end

	def rsvp
		@event = Event.find(params[:id])

		@payment_method = params[:payment_method]
		@price = params[:price].to_d
		@count = params[:count].to_i
		@total_price = @count * @price
		@price_title = "Standard"

		# VALIDATIONS

		if @event.free_event
			@price = 0
			@total_price = 0
			@payment_method = "other"
		else
			allowed_prices = [@event.cost]
			allowed_prices << @event.discounted_cost if @event.allow_discount
			if !allowed_prices.include?(@price)
				redirect_to event_url(@event), :alert => "Price not acceptible"
				return
			end

			@price_title = @event.discounted_text if @price == @event.discounted_cost
		end

		if !["other", "paypal", "3rd_party"].include?(@payment_method)
			redirect_to event_url(@event), :notice => 'Payment method not acceptible.'
			return
		end

		if (@event.spots_left - @count) < 0
			redirect_to event_url(@event), :alert => 'There are no spots available for that event.'
			return
		end

		#if user_signed_in? && @event.attendees.include?(current_user)
		#	redirect_to event_url(@event), :notice => 'You are already attending that event.'
		#	return
		#end

		other_rsvp_payment if @payment_method == "other"
		paypal_rsvp_payment if @payment_method == "paypal"
		rd_party_rsvp_payment if @payment_method == "3rd_party"
	end

	def unrsvp
		@event = Event.find(params[:id])
		unless user_signed_in?
			session[:return_url] = unrsvp_event_url(@event)
			redirect_to new_user_session_url, :notice => 'You must sign in to unRSVP.'
			return
		end
		if @event.attendees.include?(current_user)
			@event.attendees.delete(current_user)
			redirect_to @event, :notice => 'You have unregistered to attend the event.'
		else
			redirect_to events_url, :alert => 'You are not attending that event.'
		end
	end

	private

	def process_events_search
		if request.xhr?
			if params[:event_type]
				types = params[:event_type].split(/,/)
				if types.count > 0
					ews = []
					types.each do |t|
						ews << "type = '#{t}'"
					end
					@events = @events.where(ews.join(" OR "))
				end
			end
			if params[:event_region]
				types = params[:event_region].split(/,/)
				if types.count > 0
					ews = []
					types.each do |t|
						ews << "event_region = '#{t}'"
					end
					@events = @events.where(ews.join(" OR "))
				end
			end
			if params[:contemporary_issue]
				ids = params[:contemporary_issue].split(/,/)
				if ids.count > 0
					ciws = []
					ids.each do |id|
						ciws << "contemporary_issues_events.contemporary_issue_id = #{id}"
					end
					@events = @events.joins("JOIN contemporary_issues_events ON contemporary_issues_events.event_id = events.id").where(ciws.join(" OR "))
				end
			end
			if params[:chapter]
				ids = params[:chapter].split(/,/)
				if ids.count > 0
					cws = []
					ids.each do |id|
						cws << "chapter_id = #{id}"
					end
					@events = @events.where(cws.join(" OR "))
				end
			end
			if params[:person_type]
				ids = params[:person_type].split(/,/)
				if ids.count > 0
					ptws = []
					ids.each do |id|
						ptws << "events_person_types.person_type_id = #{id}"
					end
					@events = @events.joins("JOIN events_person_types ON events_person_types.event_id = events.id").where(ptws.join(" OR "))
				end
			end
			@events = @events.uniq
			render :action => 'ajax_list', :layout => false
			return
		end
		render :action => 'index'
	end

	def other_rsvp_payment
		if !@event.free_event && !@event.allow_other_payment_type
			redirect_to event_url(@event), :alert => 'That payment method is not accepted for this event.'
			return
		end
		@attendee_event = AttendeesEvent.new
		if user_signed_in?
			@attendee_event.attendee = current_user
		else
			@attendee_event.email = params[:attendees_event][:email]
			@attendee_event.first_name = params[:attendees_event][:first_name]
			@attendee_event.last_name = params[:attendees_event][:last_name]
		end
		@attendee_event.event = @event
		@attendee_event.count = @count
		@attendee_event.total_cost = @total_price
		@attendee_event.created_at = Time.now
		@attendee_event.updated_at = Time.now

		if @attendee_event.save
			UserMailer.event_registered_user(@event, @attendee_event).deliver
			UserMailer.event_registered_admin(@event, @attendee_event, nil).deliver
			redirect_to @event, :notice => 'You have registered to attend the event.'
		else
			render :action => "show"
		end
	end

	def paypal_rsvp_payment
		if !@event.allow_paypal
			redirect_to event_url(@event), :alert => 'That payment method is not accepted for this event.'
			return
		end

		payment_confirmation = PaymentConfirmation.new
		payment_confirmation.event = @event
		if user_signed_in?
			payment_confirmation.user = current_user
		end
		if payment_confirmation.save
			item_name = "#{@event.title} (#{@price_title})"
			invoice_id = payment_confirmation.id
			redirect_to "#{paypal_url(@event, invoice_id, 0)}&quantity_1=#{@count}&amount_1=#{@price}&item_name_1=" + URI.encode(item_name)
			return
		else
			redirect_to event_path(@event), :alert => "Error redirecting to paypal for payment."
			return
		end
	end

	def rd_party_rsvp_payment
		if !@event.allow_3rd_party_payment
			redirect_to event_url(@event), :alert => 'That payment method is not accepted for this event.'
			return
		end

		redirect_to event_path(@event)
		return
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.haml
= semantic_form_for [:admin, @event] do |f|
	= f.input :type, :collection => Event.types
	= f.input :featured
	= f.input :event_region, :collection => Event.event_regions, :include_blank => false, :selected => "USA"
	= f.input :title
	= f.input :image 
	= remove_image_tag(f, @event)
	= f.input :body, :input_html => { :class => 'js_editor' }
	= f.input :teaser, :input_html => { :class => 'js_editor' }
	= f.input :chapter, :collection => Chapter.all.collect { |c| [c.name, c.id] }
	= f.input :location, :collection => Location.all.collect { |c| [c.name, c.id] }
	- @speakers =User.where(:speaker => true).collect { |c| [c.full_name, c.id] }.sort_by() { |c| c[0]}
	= f.input :speakers, :collection => @speakers, :input_html => { :class => 'js_multiselect' }, :label => 'Speaker / Panelist'
	- @celebrants =User.where(:celebrant => true).collect { |c| [c.full_name, c.id] }.sort_by() { |c| c[0]}
	= f.input :celebrants, :collection => @celebrants, :input_html => { :class => 'js_multiselect' }, :label => 'Celebrants'
	= f.input :director, :collection => User.all.collect { |c| [c.full_name, c.id] }.sort_by {|c| c[0]}, :label => "Program Contact"
	= f.input :related_events, :collection => Event.find(:all, :order => "title") , :input_html => { :class => 'js_multiselect' }, :label => "Related Events"
	= f.input :spots_available
	= f.input :start_date, :as => :string, :input_html => { :class => 'js_start_date' }
	= f.input :end_date, :as => :string, :input_html => { :class => 'js_end_date' }
	= f.input :contemporary_issues, :collection => ContemporaryIssue.published.order(:title).collect { |c| [c.title, c.id] }, :input_html => { :class => 'js_multiselect' }
	= f.input :person_types, :collection => PersonType.published.collect { |c| [c.name, c.id] }.sort_by() { |c| c[0]}, :input_html => { :class => 'js_multiselect' }
	= f.inputs :name => 'Pricing' do
		= f.input :free_event
		= f.input :allow_paypal
		= f.input :allow_other_payment_type, :label => "Allow other CAPP payment type (ex. by check)"
		.other_payment
			= f.input :other_payment_type_text, :label=>"Other CAPP payment type text (ex. \"Pay by check\")"
			= f.input :other_payment_type_instructions, :label=>"Other Other payment type instructions (ex. add address and who to make the check out to)"
		= f.input :allow_3rd_party_payment, :label => "Allow 3rd party Payment gateway"
		.other_payment_3rd_party
			= f.input :allow_3rd_party_payment_url, :label=>"3rd Party Payment Link (ex. \"www.fordham.edu\")"
			= f.input :allow_3rd_party_payment_type_instructions, :label=>"3rd Party Payment Link text (ex. \"Register and Pay at Fordham University Online\")"
		.allow_discount
			= f.input :allow_discount
			= f.input :discounted_text
			= f.input :discounted_cost
		- if @event.cost == nil
			- @event.cost = 0 
		= f.input :cost, :input_html => { :value => @event.cost} 
		= f.input :display_advanced_payment_options, :label => "Display Advanced Payment Options?"
		.advanced_payment_form
			= f.input :advanced_payment_form
			- if @event.advanced_payment_form_file_name?
				= f.input :delete_advanced_payment_form, :as => :boolean, :label => "Remove form?"
		
	= f.buttons

:javascript
	$(document).ready(function() {
		var message_other_payment="\"Allow 3rd party Payment gateway\" does not support other types of payments";
		initialize_values();

		function initialize_values(){
			if($("#event_allow_other_payment_type").is(":checked"))
				$(".other_payment").show();
			else
				$(".other_payment").hide();

			if($("#event_allow_3rd_party_payment").is(":checked"))
				$(".other_payment_3rd_party").show();
			else
				$(".other_payment_3rd_party").hide();

			check_free_event();
		}

		function check_free_event(){
			if($("#event_free_event").is(":checked")){
				$('#event_allow_paypal').attr("disabled", true);
				$('#event_allow_paypal').attr("checked", false);


				$('#event_allow_other_payment_type').attr("disabled", true);
				$('#event_allow_other_payment_type').attr("checked", false);
				$(".other_payment").hide();


				$('#event_allow_3rd_party_payment').attr("disabled", true);
				$('#event_allow_3rd_party_payment').attr("checked", false);
				$(".other_payment_3rd_party").hide();


				$('#event_allow_discount').attr("disabled", true);
				$('#event_allow_discount').attr("checked", false);
				$('#event_discounted_cost').attr("disabled", true);
				$('#event_discounted_cost').val("");
				$('#event_discounted_text').attr("disabled", true);
				$('#event_discounted_text').val("");


				$('#event_cost').attr("disabled", true);
				$('#event_cost').val("0.0");
				
				

			}else{
				$('#event_allow_paypal').attr("disabled", false)
				$('#event_allow_other_payment_type').attr("disabled", false)
				$('#event_allow_3rd_party_payment').attr("disabled", false)
				$('#event_cost').attr("disabled", false);
				$('#event_discounted_cost').attr("disabled", false);
				$('#event_discounted_text').attr("disabled", false);
				$('#event_allow_discount').attr("disabled", false);
			}


		}
		
		$("#event_free_event").click(function(){
			check_free_event();
		});

		$("#event_allow_paypal").click(function(){
			if($("#event_allow_3rd_party_payment").is(":checked")){
				$('#event_allow_paypal').attr("checked", false);
				alert(message_other_payment);
			}
		});

		$("#event_allow_other_payment_type").click(function(){
			if($("#event_allow_3rd_party_payment").is(":checked")){
				$('#event_allow_other_payment_type').attr("checked", false);
				alert(message_other_payment);
			}else{
				if($("#event_allow_other_payment_type").is(":checked"))
					$(".other_payment").show();
				else
					$(".other_payment").hide();
			}
		});

		$("#event_allow_3rd_party_payment").click(function(){
			if($("#event_allow_other_payment_type").is(":checked") || $("#event_allow_paypal").is(":checked")){
				$('#event_allow_3rd_party_payment').attr("checked", false);
				alert(message_other_payment);
			}else{
				if($("#event_allow_3rd_party_payment").is(":checked"))
					$(".other_payment_3rd_party").show();
				else
					$(".other_payment_3rd_party").hide();
			}
		});


		
	});

app/views/admin/events/_teaser.html.haml
%table.event_teaser
	%tr
		%td{:style => 'width: 450px'}
			%h5.event_title= teaser.title
			.event.teaser= teaser.teaser.html_safe rescue ""
			- if teaser.location
				.event_location
					Location: 
					= link_to teaser.location.name, location_path(teaser.location)
			- if teaser.speaker
				.event_speaker
					Speaker:
					= teaser.speaker.full_name
					/= link_to teaser.speaker.full_name, user_path(teaser.speaker)
		%td.event_time{:style => 'width: 90px'}
			= teaser.short_start
			%br
			= distance_of_time_in_words(teaser.duration) rescue ''
		%td.event_spots{:style => 'width: 90px'}
			%span.event_spots_available= teaser.spots_available
			spots left
		%td.rsvp
			= link_to "RSVP", event_path(teaser)

app/views/admin/events/ajax_list.html.haml
- if @events.empty?
	.no_results
		= "No results for the given filters.  Try removing some filters."
- else
	- @events.each do |event|
		.event_teaser_list_item
			= render :partial => 'teaser', :object => event
:javascript
	$('.element input').click(function() {
		var ps = collect_params();
		$('#js_events_container').load('/events/list?' + ps);
	});

	function collect_params() {
		var param_string = [];
		param_string.push(collect_params_for('event_type'));
		param_string.push(collect_params_for('contemporary_issue'));
		param_string.push(collect_params_for('chapter'));
		param_string.push(collect_params_for('person_type'));
		return(param_string.join('&'));
	}

	function collect_params_for(cat) {
		var params = [];
		/*
		if ($('.element[data-category="' + cat +'" input:checked').size() == 0) {
			return('');
		}
		*/
		$('.element[data-category="' + cat + '"] input:checked').each(function() {
			var container = $(this).closest('.element');
			params.push(escape(container.attr('data-value')));
		});
		return(cat + '=' + params.join(','));
	}

app/views/admin/events/edit.html.haml
.page
  %h2 Edit Event
  = render :partial => 'form'

app/views/admin/events/index.html.haml
.page
	%h2 All Events
	- table(@events, ['title', 'type', 'location', 'chapter', '']) do |event, klass|
		%tr{:class => klass}
			%td= link_to event.title, event_url(event)
			%td= event.type
			%td= event.location.name rescue nil
			%td= event.chapter.name rescue nil
			%td.controls
				= link_to 'Edit', edit_admin_event_path(event)
				= link_to 'Delete', admin_event_path(event), :method => :delete, :confirm => "Are you sure?"
	.link
		= link_to 'New Event', new_admin_event_url, :class => 'btn_edit left'

app/views/admin/events/new.html.haml
.page
  %h2 New Event
  = render :partial => 'form'

app/views/admin/events/show.html.haml
.event_page
  .page
    %h2= @event.title
    .event_header
      .event_time_info
        - if @event.start_date && @event.end_date
          %span.event_duration= distance_of_time_in_words(@event.end_date - @event.start_date) rescue ""
        - if @event.start_date
          %span.event_start= "Starts: #{@event.formatted_start}"
        - if @event.end_date
          %span.event_end= "Ends: #{@event.formatted_end}"
    %strong Ideal For:
    - @event.person_types.each do |person_type|
      = link_to person_type.name, person_type_path(person_type)
    .event_body= @event.body.html_safe rescue ""
    - if @event.location
      .event_location
        Main Location: 
        = link_to @event.location.name, location_path(@event.location)
    - if @event.director
      .event_director
        Contact the Program Director: 
        = @event.director.full_name
        /= link_to @event.director.full_name, user_path(@event.director)
  %hr
  .page
    %h4
      Contemporary Issues Covered:
      - @event.contemporary_issues.each do |issue|
        = link_to issue.title, contemporary_issue_path(issue), :class => 'contemporary_issue_link'