config/routes.rb
CappUsa::Application.routes.draw do
	
	resources :audio_mp3s
	resources :audio_contents

	devise_for :users,:controllers => {:registrations => "registrations"}, :path_names => { :sign_in => 'login' }
	match 'users/activate' => "users#activate", :via => :GET

	match '/2016-conference-signup', :to => "signups#index", :via => :get
	resources :signups, :except => [:new, :edit, :destroy, :update] do
		collection do 
			get :confirm
			get :error
		end
	end

	resources :sent_email_messages, :path => "mail" do
		member do
			post :send
		end
	end
	resources :contact_lists do
		collection do
			get :by_type
			get :popup
			get :user_list
		end
	end
	resources :static_contact_lists do
		member do
			post :add_contact
			post :remove_contact
			get :user_list
		end
	end
	namespace :admin do
		resources :blocks
		resources :chapters
		resources :contemporary_issues
		resources :encyclicals
		resources :events do
			member do
				get 'user_list'
			end

			resources :attendees_events do
				member do
					put "clear_cc_info"
				end
			end
		end
		resources :locations
		resources :audio_contents
		resources :audio_mp3s
		resources :menu_items
		resources :pages
		resources :person_types
		resources :principles
		resources :papal_addresses
		resources :prism_types
		resources :role_types
		resources :stories
		resources :thoughts
		resources :feed_sources
		resources :users do
			collection do
				post 'search'
			end
			member do
				post 'activate'
			end
		end
		resources :questions do
		collection do
			get 'title'
			get 'type'
			get 'summary'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
		resources :content_fragments do
			collection do
				get 'type_options/:content_fragment_type', :action => 'type_options'
			end
		end
		resources :contacts do
			collection do
				get 'raw'
			end
			member do
				post 'upgrade'
			end
		end
	end

	resources :contemporary_issues do
		member do
			get 'view'
		end
	end
	resources :encyclicals, :path => "social_encyclicals" do
		collection do
			get 'published'
			get 'popup'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
	resources :events do
		member do
			post 'advanced_rsvp'
			post 'rsvp'
			post 'unrsvp'
			get 'thanks'
		end
		collection do
			get 'past'
		end
	end
	resources :locations
	resources :person_types
	resources :principles
	resources :prism_types
	resources :role_types
	resources :stories, :path => "news"
	resources :papal_addresses
	resources :feed_entries
	resources :thoughts, :path => "social_thought"
	resources :contacts
	resources :users

	match 'display' => 'audio_contents#display'

	match 'what_is_cst' => 'home#what_is_cst'
	match 'study_center' => 'home#study_center'
	match 'about_us/capp_usa_team' => 'home#about_us_capp_usa_team'
	match 'search' => 'search#index'
	match 'encyclicals/:id/chapter/:chapter/references' => 'encyclicals#chapter_references'
	match 'encyclicals/popup' => 'encyclicals#popup'

	match 'profile' => "users#edit", :via => :get
	match 'profile' => "users#update", :via => :put

	post 'paypal_ipn', :to => 'paypal_ipn#index', :as => 'paypal_ipn'

	match '*url' => 'pages#view'

	root :to => 'home#index'



	# See how all your routes lay out with "rake routes"

	# This is a legacy wild controller route that's not recommended for RESTful applications.
	# Note: This route will make all actions in every controller accessible via GET requests.
	# match ':controller(/:action(/:id(.:format)))'
end

app/models/encyclical.rb
class Encyclical < ContentFragment
	validates :title, :presence => true
	validates :name, :presence => true
	validates :body, :presence => true

	has_many :encyclical_chapters

	def reference_keyword
		self.title.titleize.gsub(/[^A-Z]/, '')
	end

	def parsed_body
		parse_chapters
	end

	def parse_chapters
		references = EncyclicalReference.where(:encyclical_id => self.id)
		self.chapters.map { |chapter|
			number = chapter.split(".").first
			number = 0 if number.to_i.to_s != number
			refs = references.select { |c| c.chapter_number == number.to_i }
			Rails.logger.debug "chapter - #{number}"
			Rails.logger.debug "refs - #{refs.inspect}"
			ref_count_class = refs.count == 0 ? "encyclical_without_reference" : "encyclical_with_reference"
			ref_link_text = reference_link_text(refs)
			ret = "<a class='encyclical_chapter_link #{ref_count_class}' data-id='#{id}' data-chapter='#{number}' data-encyclical='#{reference_keyword}' data-name='chapter_#{number}'>#{ref_link_text}</a>"
			ret += "<div id='chapter_#{number}_reference_container' class='chapter_reference_container' style='display: none'></div>"
			ret += "<p class='chapter' id='chapter_#{number}' data-id='#{number}'>#{chapter}</p>"
			ret
		}.join("")
	end

	def reference_link_text(refs)
		refs.collect { |c|
			c.content_fragment_type
		}.uniq.compact.collect { |content_fragment_type|
			"#{content_fragment_type.titleize} (#{refs.select { |c| c.content_fragment_type == content_fragment_type }.count})"
		}.join(" ")
	end

	def self.reference_map
		@reference_map ||= Hash[*Encyclical.all.collect { |c| [c.reference_keyword, c.id] }.flatten]
	end

	def reference_name
		reference_keyword
	end

	def self.chapter_regex
		/<br \/>(?=\d+\. )/
	end

	def chapters
		self.body.split(Encyclical.chapter_regex)
	end

	def self.find_by_reference_keyword(ref)
		@search = Encyclical.search do |q|
			q.with(:reference_name, ref)
		end
		@search.results.first
	end

	def refresh_encyclical_chapters!
		self.encyclical_chapters.map(&:destroy)
		current_chapter = 0
		self.chapters.each do |chapter|
			number = chapter.split(".").first
			number = 0 if number.to_i.to_s != number
			break if number.to_i < current_chapter
			self.encyclical_chapters << EncyclicalChapter.create(:encyclical => self, :chapter_num => number, :chapter_body => chapter)
			current_chapter = number.to_i
		end
	end

end

app/controllers/admin/encyclicals_controller.rb
class Admin::EncyclicalsController < ApplicationController

	before_filter :require_admin!

	respond_to :html

	def index
		respond_with(@encyclicals = Encyclical.order(:name))
	end

	def show
		@encyclical = Encyclical.find(params[:id])
		respond_with(@encyclical)
	end

	def new
		respond_with(@encyclical = Encyclical.new)
	end

	def create
		respond_with(@encyclical = Encyclical.create(params[:encyclical]), :location => admin_encyclicals_url)
	end

	def edit
		respond_with(@encyclical = Encyclical.find(params[:id]))
	end

	def update
		@encyclical = Encyclical.update(params[:id], params[:encyclical])
		respond_with(@encyclical, :location => encyclical_path(@encyclical))
	end

	def destroy
		respond_with(@encyclical = Encyclical.delete(params[:id]), :location => admin_encyclicals_url)
	end

end

app/controllers/encyclicals_controller.rb
class EncyclicalsController < ApplicationController

	respond_to :html
	layout :determine_layout

	def index
		@encyclicals = Encyclical.published.order(:title).includes(:users)
		index_search(:title)
	end

	def published
		@encyclicals = Encyclical.published.order("published_at desc").includes(:users)
		index_search(:published_at)
		if !request.xhr?
			render :action => :index
		end
	end

	def search
		@encyclicals = Encyclical.published.order(:title).includes(:users)
		@encyclical_chapters = []
		index_search(:title)
		if !request.xhr?
			render :action => :index
		end
	end

	def show
		@encyclical = Encyclical.find(params[:id])
		unless @encyclical.published
			not_found
		else
			respond_with(@encyclical)
		end
	end

	def popup
		@encyclicals = Encyclical.published.order(:title)
	end

	def reference
		@encyclical = Encyclical.find(params[:id])
		render :action => :reference, :layout => false
	end

	def chapter_references
		@encyclical = Encyclical.find(params[:id])
		chapter = params[:chapter]
		@references = EncyclicalReference.where(:encyclical_id => @encyclical.id).where(:chapter_number => chapter).includes(:content_fragment)
		render :action => :chapter_references, :layout => false
	end

	private

	def index_search(sort)
		sort_order = :asc
		sort_order = :desc if sort == :published_at
		@encyclical_ids = params[:encyclical_id].split(/,/).delete_if { |c| c == "" } rescue []
		if request.xhr? || params[:q]
			if params[:eq] && params[:eq] != ""
				encyclical_chapter_search(sort, sort_order)
			else
				encyclical_title_search(sort, sort_order)
			end
		end
	end

	def encyclical_chapter_search(sort, sort_order)
		@search = EncyclicalChapter.search do |q|
			if params[:author]
				authors = params[:author].split(/,/)
				if authors.count > 0
					q.with(:author_ids, authors)
				end
			end
			@eq = params[:eq]
			q.fulltext @eq do
				highlight :chapter_body
			end
			if !@encyclical_ids.empty?
				q.with(:encyclical_id, @encyclical_ids)
			end
			q.facet(:encyclical_id)
			q.order_by sort, sort_order
		end
		@encyclical_chapters = @search.results
		if request.xhr?
			render :partial => 'chapter_results'#, :collection => @search.hits
			return
		end
	end

	def encyclical_title_search(sort, sort_order)
		@search = ContentFragment.search do |q|
			q.with(:type, 'Encyclical')
			if params[:author]
				authors = params[:author].split(/,/)
				if authors.count > 0
					q.with(:author_ids, authors)
				end
			end
			q.order_by sort, sort_order
		end
		@encyclicals = @search.results
		if request.xhr?
			render :partial => 'teaser', :collection => @encyclicals
			return
		end
	end

	def determine_layout
		return "tinymce_popup" if action_name == "popup"
		"application"
	end
end

app/helpers/encyclicals_helper.rb
module EncyclicalsHelper
end

app/views/admin/encyclicals/_form.html.haml
= semantic_form_for [:admin, @encyclical] do |f|
	= f.input :name
	= f.input :title
	= f.input :translated_title
	= f.input :body, :input_html => { :class => 'js_editor' }
	= f.input :published
	= f.input :published_at, :as => :string, :input_html => { :class => 'js_datetime' }
	= f.input :users, :collection => User.all.collect { |c| [c.full_name, c.id] }, :label => "Author", :input_html => { :class => 'js_multiselect' }
	= f.input :thumbnail
	= remove_thumbnail_tag(f, @encyclical)
	= f.input :image 
	= remove_image_tag(f, @encyclical)
	= f.buttons

:javascript
	$(document).ready(function(){
		var isFirefox = typeof InstallTrigger !== 'undefined';

		$('#encyclical_thumbnail').change(function(){
			validate_image($(this));
		});

		$('#encyclical_image').change(function(){
			validate_image($(this));
		});

		function validate_image(img) {
			var isJPEG= new RegExp("\.jpeg");
			var isJPG= new RegExp("\.jpg");
			var isPNG= new RegExp("\.png");
			if(isJPEG.test(img.val())==false){
				if(isJPG.test(img.val())==false){
					if(isPNG.test(img.val())==false){
						alert("Only \"jpeg\" and \"png\" files");
						var field = $(this);
						if(isFirefox)
							img.val("");
						else
							img.replaceWith(field = img.clone( true ) );
					}
				}
			}
		}
		
	});

app/views/admin/encyclicals/_list.html.haml
- list.encyclicals.each do |encyclical|
	= link_to encyclical.title, encyclical_path(encyclical), :class => 'encyclical_link'

app/views/admin/encyclicals/edit.html.haml
.page
  %h2 Edit Social Encyclical
  = render :partial => 'form'

app/views/admin/encyclicals/index.html.haml
.page
	%h2 All Social Encyclicals
	- table(@encyclicals, ['name', 'title', 'published', '']) do |encyclical, klass|
		%tr{:class => klass}
			%td= link_to encyclical.name, encyclical_path(encyclical)
			%td= encyclical.title
			%td= encyclical.published
			%td.controls
				= link_to 'Edit', edit_admin_encyclical_path(encyclical)
				= link_to 'Delete', admin_encyclical_path(encyclical), :method => :delete, :confirm => "Are you sure?"
	.link
		= link_to 'New Encyclical', new_admin_encyclical_url, :class => 'btn_edit left'

app/views/admin/encyclicals/new.html.haml
.page
  %h2 New Social Encyclical
  = render :partial => 'form'

app/views/admin/encyclicals/show.html.haml
.page
  = render :partial => 'content_fragments/page', :object => @encyclical