config/routes.rb
CappUsa::Application.routes.draw do
	
	resources :audio_mp3s
	resources :audio_contents

	devise_for :users,:controllers => {:registrations => "registrations"}, :path_names => { :sign_in => 'login' }
	match 'users/activate' => "users#activate", :via => :GET

	match '/2016-conference-signup', :to => "signups#index", :via => :get
	resources :signups, :except => [:new, :edit, :destroy, :update] do
		collection do 
			get :confirm
			get :error
		end
	end

	resources :sent_email_messages, :path => "mail" do
		member do
			post :send
		end
	end
	resources :contact_lists do
		collection do
			get :by_type
			get :popup
			get :user_list
		end
	end
	resources :static_contact_lists do
		member do
			post :add_contact
			post :remove_contact
			get :user_list
		end
	end
	namespace :admin do
		resources :blocks
		resources :chapters
		resources :contemporary_issues
		resources :encyclicals
		resources :events do
			member do
				get 'user_list'
			end

			resources :attendees_events do
				member do
					put "clear_cc_info"
				end
			end
		end
		resources :locations
		resources :audio_contents
		resources :audio_mp3s
		resources :menu_items
		resources :pages
		resources :person_types
		resources :principles
		resources :papal_addresses
		resources :prism_types
		resources :role_types
		resources :stories
		resources :thoughts
		resources :feed_sources
		resources :users do
			collection do
				post 'search'
			end
			member do
				post 'activate'
			end
		end
		resources :questions do
		collection do
			get 'title'
			get 'type'
			get 'summary'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
		resources :content_fragments do
			collection do
				get 'type_options/:content_fragment_type', :action => 'type_options'
			end
		end
		resources :contacts do
			collection do
				get 'raw'
			end
			member do
				post 'upgrade'
			end
		end
	end

	resources :contemporary_issues do
		member do
			get 'view'
		end
	end
	resources :encyclicals, :path => "social_encyclicals" do
		collection do
			get 'published'
			get 'popup'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
	resources :events do
		member do
			post 'advanced_rsvp'
			post 'rsvp'
			post 'unrsvp'
			get 'thanks'
		end
		collection do
			get 'past'
		end
	end
	resources :locations
	resources :person_types
	resources :principles
	resources :prism_types
	resources :role_types
	resources :stories, :path => "news"
	resources :papal_addresses
	resources :feed_entries
	resources :thoughts, :path => "social_thought"
	resources :contacts
	resources :users

	match 'display' => 'audio_contents#display'

	match 'what_is_cst' => 'home#what_is_cst'
	match 'study_center' => 'home#study_center'
	match 'about_us/capp_usa_team' => 'home#about_us_capp_usa_team'
	match 'search' => 'search#index'
	match 'encyclicals/:id/chapter/:chapter/references' => 'encyclicals#chapter_references'
	match 'encyclicals/popup' => 'encyclicals#popup'

	match 'profile' => "users#edit", :via => :get
	match 'profile' => "users#update", :via => :put

	post 'paypal_ipn', :to => 'paypal_ipn#index', :as => 'paypal_ipn'

	match '*url' => 'pages#view'

	root :to => 'home#index'



	# See how all your routes lay out with "rake routes"

	# This is a legacy wild controller route that's not recommended for RESTful applications.
	# Note: This route will make all actions in every controller accessible via GET requests.
	# match ':controller(/:action(/:id(.:format)))'
end

app/models/static_contact_list.rb
class StaticContactList < ContactList
	has_and_belongs_to_many :contacts
	belongs_to :user

	validates :name, :presence => true

	def display_name
		self.name
	end
end

app/controllers/static_contact_lists_controller.rb
require 'csv'

class StaticContactListsController < ApplicationController

	before_filter :require_admin!
	before_filter :load_contact_lists
	layout "mail"
	
	def index
	end

	def show
		@contact_list = ContactList.find(params[:id])
	end

	def user_list
		@contact_list = ContactList.find(params[:id])
		csv_data = CSV.generate do |csv|
			csv << ["Email", "Name"]
			@contact_list.contacts.each do |contact|
				csv << [
					contact.full_name,
					contact.email
				]
			end
		end
		send_data csv_data,
			:type => 'text/csv; charset=iso-8859-1; header=present',
			:disposition => "attachment; filename=#{@contact_list.value_name}_user_list.csv"
	end

	def new
		@contact_list = StaticContactList.new
	end

	def create
		@contact_list = StaticContactList.create(params[:static_contact_list])
		if @contact_list.save
			redirect_to static_contact_list_path(@contact_list)
		else
			render :new
		end
	end

	def edit
		@contact_list = ContactList.find(params[:id])
	end

	def update
		@contact_list = ContactList.find(params[:id])
		if @contact_list.update_attributes(params[:static_contact_list])
			redirect_to static_contact_list_path(@contact_list)
		else
			render :edit
		end
	end

	def add_contact
		@contact_list = StaticContactList.find(params[:id])
		@contact = Contact.find(params[:contact_id])
		@contact_list.contacts << @contact unless @contact_list.contacts.include?(@contact)
		@contacts = @contact_list.contacts
		render :'show', :layout => false
	end

	def remove_contact
		@contact_list = StaticContactList.find(params[:id])
		contact_ids = params[:contact_ids]
		contact_ids.split(",").each do |contact_id|
			contact = Contact.find(contact_id)
			@contact_list.contacts.delete(contact)
		end
		@contacts = @contact_list.contacts
		render :'show', :layout => false
	end

	def destroy
		@contact_list = ContactList.find(params[:id])
		@contact_list.destroy
		redirect_to static_contact_lists_path
	end
end

app/helpers/static_contact_lists_helper.rb
module StaticContactListsHelper
end

app/views/static_contact_lists/_contact_list.html.haml
.page
	%h2= @contact_list.display_name
.clear
= link_to 'Delete Selected', remove_contact_static_contact_list_path(@contact_list), :method => :delete, :id => "js_delete_selected_contacts", :class => "delete_selected_contacts btn_edit left disabled", :confirm => "Are you sure?", :remote => true
%table.data_table
	%thead
		%tr
			%th= check_box_tag :blah, 1, false, :class => "js_all_contacts"
			%th Email
			%th Name
	- @contact_list.contacts.each do |contact|
		%tr{:class => cycle("odd", "even")}
			%td= check_box_tag :contact_ids, contact.id, false, :class => "js_contact_id"
			%td= contact.email
			%td
				- if contact.account_holder?
					= link_to contact.full_name, edit_admin_user_path(contact.user, :return_url => request.url)
				- else
					= link_to contact.full_name, edit_admin_contact_path(contact.contact, :return_url => request.url)
:javascript
	$(document).ready(function() {
		$("#js_delete_selected_contacts").click(function(e) {
			e.preventDefault();
			e.stopPropagation();

			var checked = $(".js_contact_id:checked");
			var all = $(".js_contact_id");

			var ids = [];
			checked.each (function() {
				ids.push($(this).val());
			});

			if (confirm($(this).attr('data-confirm'))) {
				if (ids.length != 0) {
					if (checked.length == all.length) {
						if (!confirm("Are you sure you want to delete all of the contacts from this list?")) {
							return;
						}
					}
					$.post("#{remove_contact_static_contact_list_path(@contact_list)}", { contact_ids: ids.join(",") }, null, "script");
				}
			}
		});

		$(".js_contact_id").change(function() {
			if ($(".js_contact_id:checked").length == 0) {
				$("#js_delete_selected_contacts").addClass("disabled");
				$(".js_all_contacts").attr('checked', false);
			} else {
				$("#js_delete_selected_contacts").removeClass("disabled");
				$(".js_all_contacts").attr('checked', true);
			}
		});

		$(".js_all_contacts").change(function() {
			var checked = $(".js_contact_id:checked");
			var all = $(".js_contact_id");
			var t = $(this);

			if (t.is(":checked")) {
				if (checked.length == 0) {
					all.attr('checked', true);
					$("#js_delete_selected_contacts").removeClass("disabled");
					$(".js_all_contacts").attr('checked', true);
				} else {
					all.attr('checked', false);
					$("#js_delete_selected_contacts").addClass("disabled");
					$(".js_all_contacts").attr('checked', false);
				}
			} else {
				all.attr('checked', false);
				$("#js_delete_selected_contacts").addClass("disabled");
				$(".js_all_contacts").attr('checked', false);
			}
		});
	});

app/views/static_contact_lists/_form.html.haml
= semantic_form_for @contact_list do |f|
	= f.input :name
	= f.actions

app/views/static_contact_lists/edit.html.haml
%h2 Edit Static Contact List
= render :partial => "form"

app/views/static_contact_lists/new.html.haml
%h2 New Static Contact List
= render :partial => "form"

app/views/static_contact_lists/show.html.haml
.page.button_group
	= link_to "CSV", user_list_static_contact_list_path(@contact_list), :class => "btn_edit"
	= link_to "Delete", static_contact_list_path(@contact_list), :method => :delete, :class => "btn_edit", :confirm => "Are you sure you want to delete this list?"
	= link_to "Edit Name", edit_static_contact_list_path(@contact_list), :class => "btn_edit"
	= link_to "Add Contacts", "#", :class => "add_contacts_button btn_edit"
#contact_list_container
	= render :partial => "contact_list"
.page.button_group
	= link_to "Add Contacts", "#", :class => "add_contacts_button btn_edit"
	.clear
#contact_popup{:style => "display: none"}
:javascript
	$(document).ready(function() {
		$(".add_contacts_button").click(function(e) {
			e.preventDefault();
			$("#contact_popup").show();
			$("#contact_popup").load("#{popup_contact_lists_path}");
		});
		$("#contact_popup_container a.add_contact").live("click", function(e) {
			e.preventDefault();
			var t = $(this);
			$.post("#{add_contact_static_contact_list_path(@contact_list)}", { contact_id: t.attr('data-id') }, null, "script");
		});
	});

app/views/static_contact_lists/show.js.erb
$("#contact_list_container").html("<%= escape_javascript(render( :partial => 'contact_list')) %>");