config/routes.rb
CappUsa::Application.routes.draw do
	
	resources :audio_mp3s
	resources :audio_contents

	devise_for :users,:controllers => {:registrations => "registrations"}, :path_names => { :sign_in => 'login' }
	match 'users/activate' => "users#activate", :via => :GET

	match '/2016-conference-signup', :to => "signups#index", :via => :get
	resources :signups, :except => [:new, :edit, :destroy, :update] do
		collection do 
			get :confirm
			get :error
		end
	end

	resources :sent_email_messages, :path => "mail" do
		member do
			post :send
		end
	end
	resources :contact_lists do
		collection do
			get :by_type
			get :popup
			get :user_list
		end
	end
	resources :static_contact_lists do
		member do
			post :add_contact
			post :remove_contact
			get :user_list
		end
	end
	namespace :admin do
		resources :blocks
		resources :chapters
		resources :contemporary_issues
		resources :encyclicals
		resources :events do
			member do
				get 'user_list'
			end

			resources :attendees_events do
				member do
					put "clear_cc_info"
				end
			end
		end
		resources :locations
		resources :audio_contents
		resources :audio_mp3s
		resources :menu_items
		resources :pages
		resources :person_types
		resources :principles
		resources :papal_addresses
		resources :prism_types
		resources :role_types
		resources :stories
		resources :thoughts
		resources :feed_sources
		resources :users do
			collection do
				post 'search'
			end
			member do
				post 'activate'
			end
		end
		resources :questions do
		collection do
			get 'title'
			get 'type'
			get 'summary'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
		resources :content_fragments do
			collection do
				get 'type_options/:content_fragment_type', :action => 'type_options'
			end
		end
		resources :contacts do
			collection do
				get 'raw'
			end
			member do
				post 'upgrade'
			end
		end
	end

	resources :contemporary_issues do
		member do
			get 'view'
		end
	end
	resources :encyclicals, :path => "social_encyclicals" do
		collection do
			get 'published'
			get 'popup'
			get 'search'
			post 'search'
		end
		member do
			get 'reference'
		end
	end
	resources :events do
		member do
			post 'advanced_rsvp'
			post 'rsvp'
			post 'unrsvp'
			get 'thanks'
		end
		collection do
			get 'past'
		end
	end
	resources :locations
	resources :person_types
	resources :principles
	resources :prism_types
	resources :role_types
	resources :stories, :path => "news"
	resources :papal_addresses
	resources :feed_entries
	resources :thoughts, :path => "social_thought"
	resources :contacts
	resources :users

	match 'display' => 'audio_contents#display'

	match 'what_is_cst' => 'home#what_is_cst'
	match 'study_center' => 'home#study_center'
	match 'about_us/capp_usa_team' => 'home#about_us_capp_usa_team'
	match 'search' => 'search#index'
	match 'encyclicals/:id/chapter/:chapter/references' => 'encyclicals#chapter_references'
	match 'encyclicals/popup' => 'encyclicals#popup'

	match 'profile' => "users#edit", :via => :get
	match 'profile' => "users#update", :via => :put

	post 'paypal_ipn', :to => 'paypal_ipn#index', :as => 'paypal_ipn'

	match '*url' => 'pages#view'

	root :to => 'home#index'



	# See how all your routes lay out with "rake routes"

	# This is a legacy wild controller route that's not recommended for RESTful applications.
	# Note: This route will make all actions in every controller accessible via GET requests.
	# match ':controller(/:action(/:id(.:format)))'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@page = Page.where(:url => "/").first
		@show_right_side_bar = false
	end

	def what_is_cst
		@page = Page.where(:url => "/what_is_cst").first
	end

	def study_center
		@page = Page.where(:url => '/study_center').first
	end

	def about_us_capp_usa_team
		@page = Page.where(:url => '/about_us/capp_usa_team').first
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_event_34.html.haml
.black
	.slideshow.js_slideshow{:class => "slide1", :style => "background: url(/images/homepage-designV1_noButton.png)"}
		%a.event_34_homepage_link{:href => "/events/34"} Learn More

app/views/home/_left_menu.html.haml
:javascript
	$(function() {
		$(".top_nav").removeClass("active");
		$("#top_nav_what_is_cst_").addClass("active");
	});
#left_menu
	.left_menu_item
		= active_link_to "Overview", what_is_cst_path
	.left_menu_item
		%span PRINCIPLES:
	- Principle.published.order(:weight).each do |principle|
		.left_menu_item.left_menu_sub_item
			= active_link_to principle.name, principle_path(principle)
	.left_menu_item
		%span I AM INTERESTED IN:
	- PrismType.published.order(:weight).each do |prism_type|
		.left_menu_item.left_menu_sub_item
			= active_link_to prism_type.name, prism_type_path(prism_type)
	-#.left_menu_item
		-#%span ROLES IN CST:
	-# RoleType.published.order(:weight).each do |role_type|
		-#.left_menu_item.left_menu_sub_item
			-#= active_link_to role_type.name, role_type_path(role_type)
	-#.left_menu_item
		-#%span I AM A:
	-#- PersonType.published.order(:weight).each do |person_type|
		-#.left_menu_item.left_menu_sub_item
			-#= active_link_to person_type.name, person_type_path(person_type)

app/views/home/about_us_capp_usa_team.html.haml
-#.page
	- #if @page
		= #render :partial => 'content_fragments/page', :object => @page
	- #else
		-#Create a page with a url of "/about_us/team" to not see this page anymore.
.page
	%h2 CAPP-USA Team
.page.national_board_member_content
	%h3 National Board Members
	= render :partial => 'users/board_member', :collection => User.national_board_members.order(:about_us_weight)
.page.national_board_member_content
	%h3 Staff
	= render :partial => 'users/board_member', :collection => User.staff.order(:about_us_weight)
.page.national_board_member_content
	%h3 Chapter Covernours
	= render :partial => 'users/board_member', :collection => User.chapter_presidents.order(:about_us_weight)

app/views/home/about_us_national_board.html.haml
.page
	- if @page
		= render :partial => 'content_fragments/page', :object => @page
	- else
		Create a page with a url of "/about_us/national_board" to not see this page anymore.
.page.national_board_member_content
	%h2 National Board Members
	= render :partial => 'users/board_member', :collection => User.national_board_members
.page.national_board_member_content
	%h2 Staff
	= render :partial => 'users/board_member', :collection => User.staff
.page.national_board_member_content
	%h2 Chapter Presidents
	= render :partial => 'users/board_member', :collection => User.chapter_presidents

app/views/home/index.haml
.page
	%table.index_scroller_table
		%tr
			%td.scroller_column
				- num = 0
				/= render :partial => "event_34"
				- Thought.no_body.published.where(:feature_on_homepage => true).order("updated_at desc").each do |quote|
					- num += 1
					.black
						.slideshow.js_slideshow{:class => "slide#{num}", :style => "background: url(#{quote.image}); #{num != 1 ? "display: none" : ""}"}
							.sheen_black.sheen_homepage_title
								%table
									%tr
										%td
											%img{:width => 80, :height => 80, :src => (quote.users.first.profile_image(:small) rescue "")}
										%td.homepage_quote
											%h1
												= quote.teaser.html_safe
											%h2
												= quote.users.first.full_name rescue ''

	.about_cst 
		.strong 
			Catholic Social Teaching
		answers a question posed by Tolstoy:
		%br
		“How, then, shall we live our life?”
		%a.button_home{:href => "/what_is_cst"} Learn More
	= render :partial => 'shared/pope'
	/= render :partial => 'shared/home_upcoming_featured'
	%hr
	%table
		%tr
			%td
				.col_half
					.three_principles
						%h4.center Learn what the Catholic Church has to say about:
						- PrismType.published.where(:feature_on_homepage => true).order(:weight).limit(3).each do |prism|
							%a{:href => prism_type_url(prism)}
								.principle.menu_item_box_home
									%img{:src => prism.image, :width => 120, :height => 70}
									.bottom= prism.name

			%td
				.col_half
					.three_principles
						%h4.center Learn about the 3 Principles of Catholic Social Teaching:
						- Principle.published.where(:feature_on_homepage => true).order(:weight).limit(3).each do |principle|
							%a{:href => principle_url(principle)}
								.principle.menu_item_box_home
									%img{:src => principle.thumbnail, :width => 120, :height => 70}
									.bottom= principle.name
	%hr
	= render :partial => 'shared/episode'


%hr
- if @page
	%table#home_bottom_blocks
		%tr.thoughts_news_row
			%td.thoughts_block.col_two_three{:colspan => 2}= render :partial => 'shared/home_thoughts_block'
			%td.newscourse_block.col_three
				.newsletter_capture
					%h4 Get our Newsletter
					.arial.size11.cgrey and receive the latest CAPP-related news and information.
					= form_for Contact.new do |f|
						%table
							%tr
								%td
									= f.text_field :email, { :class => 'email_box', :id => 'js_email_address', :'data-label' => 'Add Your Email' }
									= f.text_field :first_name, { :style => 'display: none' }
									= f.text_field :last_name, { :style => 'display: none', :value => ' ' }
								%td= f.submit :class => 'submit_btn', :value=> 'Submit'
				.newsletter_capture
					%h4 Create an Account
					.arial.size11.cgrey A CAPP-USA account gives you access to sponsored Events, Courses and more.
					%a#home_signup_button{:href => new_registration_path(User)} Sign up
				= render :partial => 'shared/home_upcoming_course'
				= render :partial => 'shared/home_upcoming_event'
				.news_block= render :partial => 'shared/home_news_block'
- else
	.page
		Create a page with a url of "/" to not see this page anymore.

app/views/home/study_center.html.haml
.page.study_center
	- if @page
		= render :partial => 'content_fragments/page', :object => @page, :locals => { :hide_sub_menu => true }
	- else
		Create a page with a url of "/study_center" to not see this page anymore.
%table.study_center_blocks
	%tr.first_row
		%td.first_block
			= Block.display("study_center_courses")
			= select_tag 'courses', options_for_select({"Choose a Course" => ""}) + options_from_collection_for_select(Event.course_types, "id", "title")
			:javascript
				$("#courses").change(function() {
					id = $(this).val();
					if (id) {
						window.location = "/events/" + id;
					}
				});
		%td
			= Block.display("study_center_issues")
			= select_tag 'contemporary_issues', options_for_select({"Choose a Contemporary Issue" => ""}) + options_from_collection_for_select(ContemporaryIssue.published.order(:title), "id", "title")
			:javascript
				$("#contemporary_issues").change(function() {
					id = $(this).val();
					if (id) {
						window.location = "/social_thought?contemporary_issue="+id;
					}
				});
	%tr
		%td.first_block
			= Block.display("study_center_encyclicals")
			= select_tag 'encyclicals', options_for_select({"Choose an Encyclical" => ""}) + options_from_collection_for_select(Encyclical.published.order(:title), "id", "title")
			:javascript
				$("#encyclicals").change(function() {
					id = $(this).val();
					if (id) {
						window.location = "/social_encyclicals/" + id;
					}
				});
		%td
			= Block.display("study_center_papal_addresses")
			= select_tag 'papal_addresses', options_for_select({"Choose a Papal Address" => ""}) + options_from_collection_for_select(PapalAddress.published.order(:name), "id", "name")
			:javascript
				$("#papal_addresses").change(function() {
					id = $(this).val();
					if (id) {
						window.location = "/papal_addresses/" + id;
					}
				});

app/views/home/what_is_cst.html.haml
.page
	- if @page
		= render :partial => 'content_fragments/page', :object => @page
	- else
		Create a page with a url of "/what_is_cst" to not see this page anymore.